apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-manga2you
  # namespace: default
  # labels:
  #   app:  backend-manga2you
spec:
  selector:
    # matchLabels:
    #   app: backend-manga2you
  replicas: 1
  template:
    metadata:
      # labels:
      #   app:  backend-manga2you
    spec:

      serviceAccountName: backend-sa
      containers:
      - name: backend-manga2you-container
        image: saberbenhamda0/backend_manga2you:70
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort:  9632