# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend-manga2you
# spec:
#   template:
#     spec:
#       containers:
#         - name: backend-manga2you-container
#           resources:
#             limits:
#               cpu: 700m
#               memory: 1Gi
#             requests:
#               cpu: 500m
#               memory: 500Mi
#           envFrom:
#             - configMapRef:
#                 name: backend-manga2you-env-variables
