apiVersion: v1
kind: Service
metadata:
  name: backend-manga2you
spec:
  selector:
    app: backend-manga2you
  type: ClusterIP
  ports:
  - name: backend-manga2you-port
    protocol: TCP
    port: 9632
    targetPort: 9632