apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - HPA.yaml
  - rbac/backend/sa.yaml
  - rbac/backend/role.yaml
  - rbac/backend/role-biding.yaml


commonLabels:
  app: backend-manga2you

# we can also generate a configMapGenerator