apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scripts
  namespace: staging
data:
  test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';
    
    export let options = {
      stages: [
        { duration: '2m', target: 100 },  // Ramp up
        { duration: '5m', target: 100 },  // Stay at 100 users
        { duration: '2m', target: 200 },  // Spike
        { duration: '5m', target: 200 },
        { duration: '2m', target: 0 },    // Ramp down
      ],
    };
    
    export default function () {
      let res = http.get('http://staging-backend-manga2you-v1.staging.svc.cluster.local');
      check(res, { 'status is 200': (r) => r.status === 200 });
      sleep(1);
    }